### PR TITLE
Improve Python code style for  `keparith` module

### PR DESCRIPTION
**Pull request by milmazz**

### CODE REVIEW

**Comment by barentsen** [comment]
@milmazz Many thanks for taking the time to review the code style and submitting a pull request.  Unfortunately `PyKE` does not have unit tests at the moment, which makes it tricky to verify that the style changes do not introduce any accidental changes in the program behavior.  I would like to hold off with merging these changes, for now, until we have a way to test. What do you think?

Again, thx++ for taking this effort.

**Comment by milmazz** [comment]
@barentsen Indeed, without any Unit Tests and without Continuous Integration (e.g. TravisCI), is tricky to verify the project's consistency even if a change is minimal. I hope that this situation, in the long run, does not keep out people from collaborating.

My concern is that if somebody updates the `keparith.py` this PR surely will enter in a conflict state. 

Do you have plans to include any Unit Test suite? what do you think about [pytest](http://pytest.org/latest/)? I can help with this if you want.

Please, just let me know what do you think.

**Comment by barentsen** [comment]
@milmazz At the moment we are not actively developing `PyKE` due to time constraints.  We would certainly like to see an improved version, in particular to enable the PyRAF dependencies to be reduced or removed.  Such a new version should definitely come with unit tests.  Pytest and Travis would be a great way to go.

**Comment by mirca** [comment]
I'm closing this in favor of #5. Thanks @milmazz, anyways!

**Pull request closed without merging**
