### PR TITLE
Add default values to --help

### LINKED ISSUE #21: `--help` should show the default argument values
I believe it is important that the `--help` strings show the default argument values.

For example, `$ kepflatten --help | grep datacol` currently shows:
`--datacol DATACOL     Name of data column to plot`
it would be helpful for users to show the default value, e.g.:
`--datacol DATACOL     Name of data column to plot (default: SAP_FLUX)`

This is not a requirement for the first release however.

### PR DESCRIPTION
**Pull request by mirca**
fixes #21 
cc @barentsen

### CODE REVIEW

**Comment by mirca** [comment]
@barentsen second part is done ;-)

**Comment by barentsen** [comment]
Nice!!  I like it a lot now.  We can merge!

```
kepextract --help
usage: kepextract [-h] [--maskfile MASKFILE] [--bkg] [--overwrite] [--verbose]
                  [--logfile LOGFILE]
                  infile outfile

Derive a light curve from a target pixel file, with user-defined apertures

positional arguments:
  infile                Name of input target pixel file
  outfile               Name of output light curve FITS file

optional arguments:
  -h, --help            show this help message and exit
  --maskfile MASKFILE   Name of mask defintion ASCII file (default: ALL)
  --bkg                 Subtract background from data?
  --overwrite           Overwrite output file?
  --verbose             Write to a log file?
  --logfile LOGFILE, -l LOGFILE
                        Name of ascii log file (default: kepextract.log)
```

**Comment by barentsen** [comment]
PS: Unless it's really hard or time-consuming, I'd support you to do a PR to change the behaviour of `ArgumentDefaultsHelpFormatter` in argparse.  (Assuming people will agree that showing the default for a boolean flag is misleading.)

**Comment by mirca** [comment]
@barentsen 👍

**Comment by mirca** [comment]
@barentsen I guess this line looks wrong, right?
```
--logfile LOGFILE, -l LOGFILE
                        Name of ascii log file (default: kepextract.log)
```

Shouldn't it be something like: ``-h, --help            show this help message and exit``?

**Comment by barentsen** [comment]
I don't see a problem?

**Comment by mirca** [comment]
@barentsen something like:

```
-l, --logfile LOGFILE Name of ascii log file (default: kepextract.log)
```

**Comment by barentsen** [comment]
Ah yes, but only if it's easy to change!

**Comment by barentsen** [comment]
Actually I prefer "--logfile" first, it's much easier to read.  Long options are nice!

**Comment by mirca** [comment]
👍

**Pull request merged**
