### PR TITLE
add a bitmask that only keeps quality == 0 cadences

### PR DESCRIPTION
**Pull request by mirca**

### CODE REVIEW

**Comment by barentsen** [comment]
Have you found an example where `DEFAULT_BITMASK` keeps cadences that cause a problem for any of the pyke tools or psf fitting?  If so, we should consider adding extra flags (perhaps "possible thruster firing") to `DEFAULT_BITMASK`.

I don't think the `ZERO_BITMASK` should ever be used, because some of the flags (e.g. DETECTOR_ANOMALY) are flagged in a very large number of cadences even though they have zero negative impact on the data.

**Comment by mirca** [comment]
@barentsen Exactly! Thanks!

**Comment by mirca** [comment]
Looks like ``DetectorAnomaly: 16384`` is causing problems on the PSF fitting

**Comment by mirca** [comment]
Should I add both of them to ``DEFAULT_BITMASK``?

**Comment by mirca** [comment]
Actually, the problems in the PSF fitting are caused more by ``CollateralCosmic: 8192``

**Comment by mirca** [comment]
In the TPF I'm working on there are 20 cadences flagged as ``CollateralCosmic`` but only two of them are problematic (massive outliers).

**Comment by barentsen** [comment]
What does the image look like in those two cadences?

**Pull request merged**
