### PR TITLE
Add sensible default values to outfile

### PR DESCRIPTION
**Pull request by mirca**
work in progress to address #64

### CODE REVIEW

**Comment by barentsen** [comment]
We are going to have to update the quickstart and the three tutorials as well.

**Comment by mirca** [comment]
@barentsen @gully I appreciate any input here. Updating quickstart and tutorials now...

**Comment by barentsen** [comment]
Looks good!  My only (very minor) comment right now is that it would be nice to mention the default output name or suffix in the `--help` docstring.

**Comment by mirca** [comment]
@barentsen regarding the default output file name; how about this:

```
➜ kepbls --help
usage: kepbls [-h] [--outfile OUTFILE] [--datacol DATACOL] [--errcol ERRCOL]
              [--minper MINPER] [--maxper MAXPER] [--mindur MINDUR]
              [--maxdur MAXDUR] [--nsearch NSEARCH] [--nbins NBINS] [--plot]
              [--overwrite] [--verbose] [--logfile LOGFILE]
              infile

Perform Box-Least Square searches for periodic exoplanet transits

positional arguments:
  infile                Name of input file

optional arguments:
  -h, --help            show this help message and exit
  --outfile OUTFILE     Name of FITS file to output.If None, outfile is a
                        combination of infile andthe name of the pyke task.
                        (default: None)
  --datacol DATACOL     Name of data column to plot (default: DETSAP_FLUX)
  --errcol ERRCOL       Name of data error column to plot (default:
                        DETSAP_FLUX_ERR)
  --minper MINPER       Minimum search period [days] (default: 1.0)
  --maxper MAXPER       Maximum search period [days] (default: 30.0)
  --mindur MINDUR       Minimum transit duration [hours] (default: 0.5)
  --maxdur MAXDUR       Maximum transit duration [hours] (default: 12.0)
  --nsearch NSEARCH     Number of test periods between minper and maxper
                        (default: 1000)
  --nbins NBINS         Number of bins in the folded time series at any test
                        period (default: 1000)
  --plot                Plot result?
  --overwrite           Overwrite output file?
  --verbose             Write to a log file?
  --logfile LOGFILE, -l LOGFILE
                        Name of ascii log file (default: kepbls.log)
```

**Comment by barentsen** [comment]
I would perhaps change
`If None, outfile is a combination of infile and the name of the pyke task.`
into
`By default, the output filename will be the same as the input filename with suffix "-kepbls.fits" added.`

**Pull request merged**
